# Generated by Django 5.2.1 on 2025-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('horario', models.DateTimeField()),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('whatsapp_token', models.TextField()),
                ('phone_number_id', models.CharField(max_length=100)),
                ('google_credentials', models.FileField(blank=True, null=True, upload_to='credenciais/')),
            ],
        ),
    ]
