# Generated by Django 5.0.6 on 2025-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
