# Generated by Django 5.0.6 on 2026-04-25 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0002_contato"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="ultima_mensagem_em",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
