# Generated by Django 5.0.6 on 2026-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0003_contato_ultima_mensagem_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="nao_lidas",
            field=models.IntegerField(default=0),
        ),
    ]
