# Generated by Django 5.0.6 on 2026-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0004_contato_nao_lidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contato",
            name="ultimo_ping",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
