# Generated by Django 5.0.6 on 2026-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0005_contato_online_contato_ultimo_ping"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="digitando",
            field=models.BooleanField(default=False),
        ),
    ]
