# Generated by Django 5.0.6 on 2026-04-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0006_contato_digitando"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="arquivo",
            field=models.FileField(blank=True, null=True, upload_to="midias/"),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="tipo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
