# Generated by Django 5.0.6 on 2026-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0007_mensagem_arquivo_mensagem_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="status",
            field=models.CharField(default="sent", max_length=20),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="whatsapp_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
