# Generated by Django 5.0.6 on 2026-05-07 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0008_mensagem_status_mensagem_whatsapp_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="numero",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("verify_token", models.CharField(max_length=255)),
                ("whatsapp_access_token", models.TextField()),
                ("whatsapp_phone_number_id", models.CharField(max_length=255)),
                ("google_calendar_id", models.CharField(max_length=255)),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agendamento",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.empresa",
            ),
        ),
        migrations.AddField(
            model_name="contato",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.empresa",
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.empresa",
            ),
        ),
        migrations.CreateModel(
            name="MensagemBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chave", models.CharField(max_length=50)),
                ("mensagem", models.TextField()),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.empresa",
                    ),
                ),
            ],
        ),
    ]
