# Generated by Django 5.0.6 on 2026-05-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0010_regrabot_usuarioempresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarioempresa",
            name="role",
        ),
        migrations.AddField(
            model_name="usuarioempresa",
            name="funcao",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("atendente", "Atendente"),
                    ("suporte", "Suporte"),
                ],
                default="atendente",
                max_length=20,
            ),
        ),
    ]
