# Generated by Django 5.0.6 on 2026-05-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0011_remove_usuarioempresa_role_usuarioempresa_funcao"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="etapa_atual",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="FluxoBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtapaBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("mensagem", models.TextField()),
                ("ordem", models.IntegerField(default=0)),
                ("eh_inicial", models.BooleanField(default=False)),
                (
                    "fluxo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.fluxobot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpcaoBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_opcao", models.CharField(max_length=100)),
                (
                    "valor_esperado",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.etapabot",
                    ),
                ),
                (
                    "proxima_etapa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proximas_opcoes",
                        to="agendamentos.etapabot",
                    ),
                ),
            ],
        ),
    ]
