# Generated by Django 5.0.6 on 2026-05-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0012_contato_etapa_atual_fluxobot_etapabot_opcaobot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etapabot",
            name="ordem",
        ),
        migrations.AddField(
            model_name="etapabot",
            name="pos_x",
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name="etapabot",
            name="pos_y",
            field=models.IntegerField(default=250),
        ),
        migrations.CreateModel(
            name="ConexaoEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gatilho", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "de_etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saida",
                        to="agendamentos.etapabot",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamentos.empresa",
                    ),
                ),
                (
                    "para_etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrada",
                        to="agendamentos.etapabot",
                    ),
                ),
            ],
        ),
    ]
