# Generated by Django 5.0.6 on 2026-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0013_remove_etapabot_ordem_etapabot_pos_x_etapabot_pos_y_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="etapabot",
            name="ordem",
            field=models.IntegerField(default=0),
        ),
    ]
