# Generated by Django 5.0.6 on 2026-05-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0015_usuarioestado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="etapa_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agendamentos.etapabot",
            ),
        ),
    ]
