# Generated by Django 5.0.6 on 2026-05-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0016_alter_contato_etapa_atual"),
    ]

    operations = [
        migrations.AddField(
            model_name="conexaoetapa",
            name="opcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.opcaobot",
            ),
        ),
    ]
