# Generated by Django 5.0.6 on 2026-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0017_conexaoetapa_opcao"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="em_atendimento_humano",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contato",
            name="ultimo_atendimento",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
