# Generated by Django 5.0.6 on 2026-05-12 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0018_contato_em_atendimento_humano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="contato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agendamentos.contato",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agendamento",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
