# Generated by Django 5.0.6 on 2026-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0019_agendamento_contato_agendamento_criado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="aguardando_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contato",
            name="aguardando_horario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contato",
            name="data_temp",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
