# Generated by Django 5.0.6 on 2026-05-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agendamentos",
            "0020_contato_aguardando_data_contato_aguardando_horario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="google_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="google_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="google_calendar_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
