# Generated by Django 5.0.6 on 2026-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0021_empresa_google_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="data_agendamento_temp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
