# Generated by Django 5.0.6 on 2026-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0022_contato_data_agendamento_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="horario_temp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
